branches:
    only:
        - master
before_install:
    - npm i -g npm@latest
install:
    - npm install
    - npm run bootstrap
after_script: npm run coveralls
language: node_js
node_js:
    - node   # Current stable
    - lts/*  # Most recent LTS version,
    - 13.12  # What's wrong wih v13.13
    - 10     # Explicitly include an active LTS version
sudo: false
env:
    global:
        - NODE_ENV=test
cache:
    npm: true
    directories:
        - 'node_modules'
