before_install:
    - npm i -g npm@latest
branches:
    only:
        - master
install:
    - npm run bootstrap
after_script: npm run coveralls
language: node_js
node_js:
    - node   # Current stable
    - lts/*  # Most recent LTS version,
    - 10     # Explicitly include an active LTS version
sudo: false
node_js:
    - '12'
env:
    global:
        - NODE_ENV=test
cache:
    npm: true
    directories:
        - 'node_modules'
